### ISSUE TITLE
hehe

### ISSUE THREAD

**Issue by jrsconfitto** [JonathanTR/JonathanTR.github.io#1]
Hey bro!

Check out [your site](http://jonathantr.github.io/)

Looks good :smile:.

You should rename the repo to just jonathantr.github.io though so it shows up at a nicer url :smiling_imp:

**Comment by JonathanTR** [comment]
haha, why did I reopen this?

**Comment by JonathanTR** [comment]
TELL ME YOU @jugglingnutcase!

**Comment by jrsconfitto** [comment]
I figured there was some nugget of wisdom I gave you that you wanted to lovingly cherish?
